// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXcVXB2zxVmHfKYbM8VlMMPl0KkqRs72o',
    appId: '1:909337229171:android:e148269b479ad303657706',
    messagingSenderId: '909337229171',
    projectId: 'wisataku-capstone',
    storageBucket: 'wisataku-capstone.firebasestorage.app',
    androidClientId: '909337229171-a6lngbce4i3mubb27fc0m47rrfm5l6uh.apps.googleusercontent.com', 
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwzkseCxjo887cQR9MVNrWDZClNeVhjfE',
    appId: '1:909337229171:ios:69988952fa973052657706',
    messagingSenderId: '909337229171',
    projectId: 'wisataku-capstone',
    storageBucket: 'wisataku-capstone.firebasestorage.app',
    iosBundleId: 'com.example.capstone',
  );
}
